properties:
  imageToDeploy:  ${{ vars.REGISTRY_LOGIN_SERVER }}/codebreaker/gameapis:3.9.0-beta.${{ github.run_number }}
  registryUrl: ${{ vars.REGISTRY_LOGIN_SERVER }}
  registryUsername: ${{ secrets.REGISTRY_USERNAME }}
  registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
  containerAppName: 'codebreaker-gameapis-v3'
  containerAppEnvironment: ${{ vars.CONTAINERAPPS_ENVIRONMENT }}
  resourceGroup: 'rg-codebreaker-dev'
  location: 'westeurope'
  targetPort: 8080
  ingress: external
