# https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#container-app-examples
location: westeurope
name: codebreaker-gameapis-v3
resourceGroup: rg-codebreaker-dev # will not be used
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/mysubscription/resourceGroups/rg-codebreaker-dev/providers/Microsoft.App/managedEnvironments/${{ vars.CONTAINERAPPS_ENVIRONMENT }}
  configuration:
    secrets:
      - name: container-registry-password
        value: ${{ secrets.REGISTRY_PASSWORD }}
    ingress:
      external: true
      targetPort: 8080
    registries:
      - passwordSecretRef: container-registry-password
        server: ${{ vars.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
  template:
    containers:
      - image: ${{ vars.REGISTRY_LOGIN_SERVER }}/codebreaker/gameapis:latest
        name: gameapis