name: bot service

on:
  push:
    branches: 
      [ main ]
    paths:
    - 'ch08/CodeBreaker.Bot/**'
    - 'ch08/CodeBreaker.Bot.Tests/**'
    - '.github/workflows/shared-test.yml'
    - '.github/workflows/shared-build-image.yml'
    - '.github/workflows/shared-deploy-containerapps.yml'
    - '.github/workflows/codebreaker-bot.yml'

  workflow_dispatch:

env:
  PROJECT_NAME: 'Codebreaker.Bot'
  CONTAINER_REPOSITORY: 'codebreaker/bot'
  CONTAINER_APPNAME: 'codebreaker-bot'
  VERSION_PREFIX: '3.9.0-beta$'
  SOLUTION_PATH: 'ch08/BotService.sln'
  PROJECT_PATH: 'ch08/CodeBreaker.Bot/CodeBreaker.Bot.csproj'
    
jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: $PROJECT_NAME
      solution-path: $SOLUTION_PATH

  build-and-publish:
    needs:  build-and-test
    uses: ./.github/workflows/shared-build-image.yml
    with:
      project-path: ${{ env.PROJECT_PATH }}
      container-repository: ${{ env.CONTAINER_REPOSITORY }}
      registry-login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
      image-tags: '${{ env.VERSION_PREFIX}}${{ github.run_number }};latest'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    needs: build-and-publish
    uses: ./.github/workflows/shared-deploy-containerapps.yml
    with:
      container-repository: $CONTAINER_REPOSITORY
      registry-login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
      container-appname: $CONTAINER_APPNAME
      image-tag: $VERSION_PREFIX{{ github.run_number }}'
      resource-group: 'rg-codebreaker-dev'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
