name: gameapis service

on:
  push:
    branches: 
      [ main ]
    paths:
    - 'ch08/Codebreaker.GameAPIs/**'
    - '.github/workflows/shared-test.yml'
    - '.github/workflows/shared-build-image.yml'
    - '.github/workflows/shared-deploy-containerapps.yml'
    - '.github/workflows/codebreaker-gameapis.yml'

  workflow_dispatch:
    
jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: 'Codebreaker.GameAPIs'
      solution-path: 'ch08/GamesService.sln'

  build-and-publish:
    needs:  build-and-test
    uses: ./.github/workflows/shared-build-image.yml
    with:
      project-path: 'ch08/Codebreaker.GameAPIs/Codebreaker.GameAPIs.csproj'
      container-repository: 'codebreaker/gameapis'
      image-tags: '3.9.0-beta.${{ github.run_number }};latest'
    secrets: inherit

  deploy:
    needs: build-and-publish
    uses: ./.github/workflows/shared-deploy-containerapps.yml
    with:
      container-repository: 'codebreaker/gameapis'   
      container-appname: 'codebreaker-gameapis-v3'
      image-tag: '3.9.0-beta.${{ github.run_number }}'
      resource-group: 'rg-codebreaker-dev'
      location: 'westeurope'
    secrets: inherit
