name: gameapis service

on:
  push:
    branches: 
      [ main, container-app-github-action-yml-config ]
    paths:
    - 'ch08/Codebreaker.GameAPIs/**'
    - '.github/workflows/shared-test.yml'
    - '.github/workflows/shared-build-image.yml'
    - '.github/workflows/shared-deploy-containerapps-yamlconfig.yml'
    - '.github/workflows/codebreaker-bot.yml'

  workflow_dispatch:
    
jobs:
  build-and-test:
    uses: ./.github/workflows/shared-test.yml
    with:
      project-name: 'Codebreaker.GameAPIs'
      solution-path: 'ch08/GamesService.sln'

  build-and-publish:
    needs:  build-and-test
    uses: ./.github/workflows/shared-build-image.yml
    with:
      project-path: 'ch08/Codebreaker.GameAPIs/Codebreaker.GameAPIs.csproj'
      container-repository: 'codebreaker/gameapis'
      registry-login-server: ${{ vars.REGISTRY_LOGIN_SERVER }}
      image-tags: '3.9.0-beta.${{ github.run_number }};latest'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    needs: build-and-publish
    uses: ./.github/workflows/shared-deploy-containerapps-yamlconfig.yml
    with:
      yaml-config-path: ./ch08/infrastructure/gamesapi-config.yml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
