name: Shared workflow to deploy to Azure Container Apps (using YML config)

on:
  workflow_call:
    inputs:
      resource-group:
        description: 'The name of the resource group'
        required: true
        type: string
      yaml-config-path:
        description: 'The path to the YAML file containing the configuration for the container app'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: 'The credentials to use for Azure'
        required: true
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          yamlConfigPath: ${{ inputs.yaml-config-path }}
          resourceGroup: ${{ inputs.resource-group }}