name: Shared workflow to deploy to Azure Container Apps

on:
  workflow_call:
    inputs:
      container-repository:
        description: 'The name of the Docker image'
        required: true
        type: string
      registry-login-server:
        description: 'The login server of the ACR'
        required: true
        type: string        
      acr-name:
        description: 'The name of the ACR (not the login server)'
        required: true
        type: string
      container-appname:
        description: 'The name of the container app'
        required: true
        type: string
      image-tag:
        description: 'The tag to use for the Docker image'
        required: true
        type: string
      resource-group:
        description: 'The name of the resource group'
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        description: 'The username of the ACR'
        required: true
      REGISTRY_PASSWORD:
        description: 'The password of the ACR'
        required: true
      AZURE_CREDENTIALS:
        description: 'The credentials to use for Azure'
        required: true
      
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

      - name: login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.registry-login-server }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}    

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy:  ${{ inputs.container-repository }}:${{ inputs.image-tag }}
          acrName: ${{ inputs.acr-name }}
          acrUsername: ${{ secrets.REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ inputs.container-appname }}
          resourceGroup: ${{ inputs.resource-group }}
          targetPort: 8080
          ingress: external
